/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreDescribeResourceUsageResponse struct for CoreDescribeResourceUsageResponse
type CoreDescribeResourceUsageResponse struct {
	Message *string `json:"message,omitempty"`
	Result *[]CloudmgrcommonIaasResource `json:"result,omitempty"`
	Status *int32 `json:"status,omitempty"`
}

// NewCoreDescribeResourceUsageResponse instantiates a new CoreDescribeResourceUsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreDescribeResourceUsageResponse() *CoreDescribeResourceUsageResponse {
	this := CoreDescribeResourceUsageResponse{}
	return &this
}

// NewCoreDescribeResourceUsageResponseWithDefaults instantiates a new CoreDescribeResourceUsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreDescribeResourceUsageResponseWithDefaults() *CoreDescribeResourceUsageResponse {
	this := CoreDescribeResourceUsageResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CoreDescribeResourceUsageResponse) GetMessage() string {
	if o == nil || o.Message == nil {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeResourceUsageResponse) GetMessageOk() (*string, bool) {
	if o == nil || o.Message == nil {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CoreDescribeResourceUsageResponse) HasMessage() bool {
	if o != nil && o.Message != nil {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CoreDescribeResourceUsageResponse) SetMessage(v string) {
	o.Message = &v
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *CoreDescribeResourceUsageResponse) GetResult() []CloudmgrcommonIaasResource {
	if o == nil || o.Result == nil {
		var ret []CloudmgrcommonIaasResource
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeResourceUsageResponse) GetResultOk() (*[]CloudmgrcommonIaasResource, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *CoreDescribeResourceUsageResponse) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given []CloudmgrcommonIaasResource and assigns it to the Result field.
func (o *CoreDescribeResourceUsageResponse) SetResult(v []CloudmgrcommonIaasResource) {
	o.Result = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CoreDescribeResourceUsageResponse) GetStatus() int32 {
	if o == nil || o.Status == nil {
		var ret int32
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeResourceUsageResponse) GetStatusOk() (*int32, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CoreDescribeResourceUsageResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given int32 and assigns it to the Status field.
func (o *CoreDescribeResourceUsageResponse) SetStatus(v int32) {
	o.Status = &v
}

func (o CoreDescribeResourceUsageResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Message != nil {
		toSerialize["message"] = o.Message
	}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableCoreDescribeResourceUsageResponse struct {
	value *CoreDescribeResourceUsageResponse
	isSet bool
}

func (v NullableCoreDescribeResourceUsageResponse) Get() *CoreDescribeResourceUsageResponse {
	return v.value
}

func (v *NullableCoreDescribeResourceUsageResponse) Set(val *CoreDescribeResourceUsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreDescribeResourceUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreDescribeResourceUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreDescribeResourceUsageResponse(val *CoreDescribeResourceUsageResponse) *NullableCoreDescribeResourceUsageResponse {
	return &NullableCoreDescribeResourceUsageResponse{value: val, isSet: true}
}

func (v NullableCoreDescribeResourceUsageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreDescribeResourceUsageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


