/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreStopServiceRequest struct for CoreStopServiceRequest
type CoreStopServiceRequest struct {
	Force *bool `json:"force,omitempty"`
}

// NewCoreStopServiceRequest instantiates a new CoreStopServiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreStopServiceRequest() *CoreStopServiceRequest {
	this := CoreStopServiceRequest{}
	return &this
}

// NewCoreStopServiceRequestWithDefaults instantiates a new CoreStopServiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreStopServiceRequestWithDefaults() *CoreStopServiceRequest {
	this := CoreStopServiceRequest{}
	return &this
}

// GetForce returns the Force field value if set, zero value otherwise.
func (o *CoreStopServiceRequest) GetForce() bool {
	if o == nil || o.Force == nil {
		var ret bool
		return ret
	}
	return *o.Force
}

// GetForceOk returns a tuple with the Force field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreStopServiceRequest) GetForceOk() (*bool, bool) {
	if o == nil || o.Force == nil {
		return nil, false
	}
	return o.Force, true
}

// HasForce returns a boolean if a field has been set.
func (o *CoreStopServiceRequest) HasForce() bool {
	if o != nil && o.Force != nil {
		return true
	}

	return false
}

// SetForce gets a reference to the given bool and assigns it to the Force field.
func (o *CoreStopServiceRequest) SetForce(v bool) {
	o.Force = &v
}

func (o CoreStopServiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Force != nil {
		toSerialize["force"] = o.Force
	}
	return json.Marshal(toSerialize)
}

type NullableCoreStopServiceRequest struct {
	value *CoreStopServiceRequest
	isSet bool
}

func (v NullableCoreStopServiceRequest) Get() *CoreStopServiceRequest {
	return v.value
}

func (v *NullableCoreStopServiceRequest) Set(val *CoreStopServiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreStopServiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreStopServiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreStopServiceRequest(val *CoreStopServiceRequest) *NullableCoreStopServiceRequest {
	return &NullableCoreStopServiceRequest{value: val, isSet: true}
}

func (v NullableCoreStopServiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreStopServiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


