/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreResizeServiceVolumesRequest struct for CoreResizeServiceVolumesRequest
type CoreResizeServiceVolumesRequest struct {
	TargetVolumeSize *map[string]interface{} `json:"target_volume_size,omitempty"`
}

// NewCoreResizeServiceVolumesRequest instantiates a new CoreResizeServiceVolumesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreResizeServiceVolumesRequest() *CoreResizeServiceVolumesRequest {
	this := CoreResizeServiceVolumesRequest{}
	return &this
}

// NewCoreResizeServiceVolumesRequestWithDefaults instantiates a new CoreResizeServiceVolumesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreResizeServiceVolumesRequestWithDefaults() *CoreResizeServiceVolumesRequest {
	this := CoreResizeServiceVolumesRequest{}
	return &this
}

// GetTargetVolumeSize returns the TargetVolumeSize field value if set, zero value otherwise.
func (o *CoreResizeServiceVolumesRequest) GetTargetVolumeSize() map[string]interface{} {
	if o == nil || o.TargetVolumeSize == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.TargetVolumeSize
}

// GetTargetVolumeSizeOk returns a tuple with the TargetVolumeSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreResizeServiceVolumesRequest) GetTargetVolumeSizeOk() (*map[string]interface{}, bool) {
	if o == nil || o.TargetVolumeSize == nil {
		return nil, false
	}
	return o.TargetVolumeSize, true
}

// HasTargetVolumeSize returns a boolean if a field has been set.
func (o *CoreResizeServiceVolumesRequest) HasTargetVolumeSize() bool {
	if o != nil && o.TargetVolumeSize != nil {
		return true
	}

	return false
}

// SetTargetVolumeSize gets a reference to the given map[string]interface{} and assigns it to the TargetVolumeSize field.
func (o *CoreResizeServiceVolumesRequest) SetTargetVolumeSize(v map[string]interface{}) {
	o.TargetVolumeSize = &v
}

func (o CoreResizeServiceVolumesRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.TargetVolumeSize != nil {
		toSerialize["target_volume_size"] = o.TargetVolumeSize
	}
	return json.Marshal(toSerialize)
}

type NullableCoreResizeServiceVolumesRequest struct {
	value *CoreResizeServiceVolumesRequest
	isSet bool
}

func (v NullableCoreResizeServiceVolumesRequest) Get() *CoreResizeServiceVolumesRequest {
	return v.value
}

func (v *NullableCoreResizeServiceVolumesRequest) Set(val *CoreResizeServiceVolumesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreResizeServiceVolumesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreResizeServiceVolumesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreResizeServiceVolumesRequest(val *CoreResizeServiceVolumesRequest) *NullableCoreResizeServiceVolumesRequest {
	return &NullableCoreResizeServiceVolumesRequest{value: val, isSet: true}
}

func (v NullableCoreResizeServiceVolumesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreResizeServiceVolumesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


