/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// OpsDescribeOpeningBankResponse struct for OpsDescribeOpeningBankResponse
type OpsDescribeOpeningBankResponse struct {
	AccountName *string `json:"account_name,omitempty"`
	AccountNumber *string `json:"account_number,omitempty"`
	BankSwiftCode *string `json:"bank_swift_code,omitempty"`
	OpeningBank *string `json:"opening_bank,omitempty"`
}

// NewOpsDescribeOpeningBankResponse instantiates a new OpsDescribeOpeningBankResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsDescribeOpeningBankResponse() *OpsDescribeOpeningBankResponse {
	this := OpsDescribeOpeningBankResponse{}
	return &this
}

// NewOpsDescribeOpeningBankResponseWithDefaults instantiates a new OpsDescribeOpeningBankResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsDescribeOpeningBankResponseWithDefaults() *OpsDescribeOpeningBankResponse {
	this := OpsDescribeOpeningBankResponse{}
	return &this
}

// GetAccountName returns the AccountName field value if set, zero value otherwise.
func (o *OpsDescribeOpeningBankResponse) GetAccountName() string {
	if o == nil || o.AccountName == nil {
		var ret string
		return ret
	}
	return *o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeOpeningBankResponse) GetAccountNameOk() (*string, bool) {
	if o == nil || o.AccountName == nil {
		return nil, false
	}
	return o.AccountName, true
}

// HasAccountName returns a boolean if a field has been set.
func (o *OpsDescribeOpeningBankResponse) HasAccountName() bool {
	if o != nil && o.AccountName != nil {
		return true
	}

	return false
}

// SetAccountName gets a reference to the given string and assigns it to the AccountName field.
func (o *OpsDescribeOpeningBankResponse) SetAccountName(v string) {
	o.AccountName = &v
}

// GetAccountNumber returns the AccountNumber field value if set, zero value otherwise.
func (o *OpsDescribeOpeningBankResponse) GetAccountNumber() string {
	if o == nil || o.AccountNumber == nil {
		var ret string
		return ret
	}
	return *o.AccountNumber
}

// GetAccountNumberOk returns a tuple with the AccountNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeOpeningBankResponse) GetAccountNumberOk() (*string, bool) {
	if o == nil || o.AccountNumber == nil {
		return nil, false
	}
	return o.AccountNumber, true
}

// HasAccountNumber returns a boolean if a field has been set.
func (o *OpsDescribeOpeningBankResponse) HasAccountNumber() bool {
	if o != nil && o.AccountNumber != nil {
		return true
	}

	return false
}

// SetAccountNumber gets a reference to the given string and assigns it to the AccountNumber field.
func (o *OpsDescribeOpeningBankResponse) SetAccountNumber(v string) {
	o.AccountNumber = &v
}

// GetBankSwiftCode returns the BankSwiftCode field value if set, zero value otherwise.
func (o *OpsDescribeOpeningBankResponse) GetBankSwiftCode() string {
	if o == nil || o.BankSwiftCode == nil {
		var ret string
		return ret
	}
	return *o.BankSwiftCode
}

// GetBankSwiftCodeOk returns a tuple with the BankSwiftCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeOpeningBankResponse) GetBankSwiftCodeOk() (*string, bool) {
	if o == nil || o.BankSwiftCode == nil {
		return nil, false
	}
	return o.BankSwiftCode, true
}

// HasBankSwiftCode returns a boolean if a field has been set.
func (o *OpsDescribeOpeningBankResponse) HasBankSwiftCode() bool {
	if o != nil && o.BankSwiftCode != nil {
		return true
	}

	return false
}

// SetBankSwiftCode gets a reference to the given string and assigns it to the BankSwiftCode field.
func (o *OpsDescribeOpeningBankResponse) SetBankSwiftCode(v string) {
	o.BankSwiftCode = &v
}

// GetOpeningBank returns the OpeningBank field value if set, zero value otherwise.
func (o *OpsDescribeOpeningBankResponse) GetOpeningBank() string {
	if o == nil || o.OpeningBank == nil {
		var ret string
		return ret
	}
	return *o.OpeningBank
}

// GetOpeningBankOk returns a tuple with the OpeningBank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeOpeningBankResponse) GetOpeningBankOk() (*string, bool) {
	if o == nil || o.OpeningBank == nil {
		return nil, false
	}
	return o.OpeningBank, true
}

// HasOpeningBank returns a boolean if a field has been set.
func (o *OpsDescribeOpeningBankResponse) HasOpeningBank() bool {
	if o != nil && o.OpeningBank != nil {
		return true
	}

	return false
}

// SetOpeningBank gets a reference to the given string and assigns it to the OpeningBank field.
func (o *OpsDescribeOpeningBankResponse) SetOpeningBank(v string) {
	o.OpeningBank = &v
}

func (o OpsDescribeOpeningBankResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccountName != nil {
		toSerialize["account_name"] = o.AccountName
	}
	if o.AccountNumber != nil {
		toSerialize["account_number"] = o.AccountNumber
	}
	if o.BankSwiftCode != nil {
		toSerialize["bank_swift_code"] = o.BankSwiftCode
	}
	if o.OpeningBank != nil {
		toSerialize["opening_bank"] = o.OpeningBank
	}
	return json.Marshal(toSerialize)
}

type NullableOpsDescribeOpeningBankResponse struct {
	value *OpsDescribeOpeningBankResponse
	isSet bool
}

func (v NullableOpsDescribeOpeningBankResponse) Get() *OpsDescribeOpeningBankResponse {
	return v.value
}

func (v *NullableOpsDescribeOpeningBankResponse) Set(val *OpsDescribeOpeningBankResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsDescribeOpeningBankResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsDescribeOpeningBankResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsDescribeOpeningBankResponse(val *OpsDescribeOpeningBankResponse) *NullableOpsDescribeOpeningBankResponse {
	return &NullableOpsDescribeOpeningBankResponse{value: val, isSet: true}
}

func (v NullableOpsDescribeOpeningBankResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsDescribeOpeningBankResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


