/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreDescribeBucketResponse struct for CoreDescribeBucketResponse
type CoreDescribeBucketResponse struct {
	CreatedAt *string `json:"created_at,omitempty"`
	DestroyedAt *string `json:"destroyed_at,omitempty"`
	Id *string `json:"id,omitempty"`
	InternalRegion *string `json:"internal_region,omitempty"`
	Name *string `json:"name,omitempty"`
	PublicRegion *string `json:"public_region,omitempty"`
	Service *string `json:"service,omitempty"`
	Status *string `json:"status,omitempty"`
	Tenant *string `json:"tenant,omitempty"`
	Vendor *string `json:"vendor,omitempty"`
}

// NewCoreDescribeBucketResponse instantiates a new CoreDescribeBucketResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreDescribeBucketResponse() *CoreDescribeBucketResponse {
	this := CoreDescribeBucketResponse{}
	return &this
}

// NewCoreDescribeBucketResponseWithDefaults instantiates a new CoreDescribeBucketResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreDescribeBucketResponseWithDefaults() *CoreDescribeBucketResponse {
	this := CoreDescribeBucketResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CoreDescribeBucketResponse) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeBucketResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CoreDescribeBucketResponse) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *CoreDescribeBucketResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDestroyedAt returns the DestroyedAt field value if set, zero value otherwise.
func (o *CoreDescribeBucketResponse) GetDestroyedAt() string {
	if o == nil || o.DestroyedAt == nil {
		var ret string
		return ret
	}
	return *o.DestroyedAt
}

// GetDestroyedAtOk returns a tuple with the DestroyedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeBucketResponse) GetDestroyedAtOk() (*string, bool) {
	if o == nil || o.DestroyedAt == nil {
		return nil, false
	}
	return o.DestroyedAt, true
}

// HasDestroyedAt returns a boolean if a field has been set.
func (o *CoreDescribeBucketResponse) HasDestroyedAt() bool {
	if o != nil && o.DestroyedAt != nil {
		return true
	}

	return false
}

// SetDestroyedAt gets a reference to the given string and assigns it to the DestroyedAt field.
func (o *CoreDescribeBucketResponse) SetDestroyedAt(v string) {
	o.DestroyedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CoreDescribeBucketResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeBucketResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CoreDescribeBucketResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CoreDescribeBucketResponse) SetId(v string) {
	o.Id = &v
}

// GetInternalRegion returns the InternalRegion field value if set, zero value otherwise.
func (o *CoreDescribeBucketResponse) GetInternalRegion() string {
	if o == nil || o.InternalRegion == nil {
		var ret string
		return ret
	}
	return *o.InternalRegion
}

// GetInternalRegionOk returns a tuple with the InternalRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeBucketResponse) GetInternalRegionOk() (*string, bool) {
	if o == nil || o.InternalRegion == nil {
		return nil, false
	}
	return o.InternalRegion, true
}

// HasInternalRegion returns a boolean if a field has been set.
func (o *CoreDescribeBucketResponse) HasInternalRegion() bool {
	if o != nil && o.InternalRegion != nil {
		return true
	}

	return false
}

// SetInternalRegion gets a reference to the given string and assigns it to the InternalRegion field.
func (o *CoreDescribeBucketResponse) SetInternalRegion(v string) {
	o.InternalRegion = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CoreDescribeBucketResponse) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeBucketResponse) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CoreDescribeBucketResponse) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CoreDescribeBucketResponse) SetName(v string) {
	o.Name = &v
}

// GetPublicRegion returns the PublicRegion field value if set, zero value otherwise.
func (o *CoreDescribeBucketResponse) GetPublicRegion() string {
	if o == nil || o.PublicRegion == nil {
		var ret string
		return ret
	}
	return *o.PublicRegion
}

// GetPublicRegionOk returns a tuple with the PublicRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeBucketResponse) GetPublicRegionOk() (*string, bool) {
	if o == nil || o.PublicRegion == nil {
		return nil, false
	}
	return o.PublicRegion, true
}

// HasPublicRegion returns a boolean if a field has been set.
func (o *CoreDescribeBucketResponse) HasPublicRegion() bool {
	if o != nil && o.PublicRegion != nil {
		return true
	}

	return false
}

// SetPublicRegion gets a reference to the given string and assigns it to the PublicRegion field.
func (o *CoreDescribeBucketResponse) SetPublicRegion(v string) {
	o.PublicRegion = &v
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *CoreDescribeBucketResponse) GetService() string {
	if o == nil || o.Service == nil {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeBucketResponse) GetServiceOk() (*string, bool) {
	if o == nil || o.Service == nil {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *CoreDescribeBucketResponse) HasService() bool {
	if o != nil && o.Service != nil {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *CoreDescribeBucketResponse) SetService(v string) {
	o.Service = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CoreDescribeBucketResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeBucketResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CoreDescribeBucketResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CoreDescribeBucketResponse) SetStatus(v string) {
	o.Status = &v
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *CoreDescribeBucketResponse) GetTenant() string {
	if o == nil || o.Tenant == nil {
		var ret string
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeBucketResponse) GetTenantOk() (*string, bool) {
	if o == nil || o.Tenant == nil {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *CoreDescribeBucketResponse) HasTenant() bool {
	if o != nil && o.Tenant != nil {
		return true
	}

	return false
}

// SetTenant gets a reference to the given string and assigns it to the Tenant field.
func (o *CoreDescribeBucketResponse) SetTenant(v string) {
	o.Tenant = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *CoreDescribeBucketResponse) GetVendor() string {
	if o == nil || o.Vendor == nil {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeBucketResponse) GetVendorOk() (*string, bool) {
	if o == nil || o.Vendor == nil {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *CoreDescribeBucketResponse) HasVendor() bool {
	if o != nil && o.Vendor != nil {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *CoreDescribeBucketResponse) SetVendor(v string) {
	o.Vendor = &v
}

func (o CoreDescribeBucketResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.DestroyedAt != nil {
		toSerialize["destroyed_at"] = o.DestroyedAt
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.InternalRegion != nil {
		toSerialize["internal_region"] = o.InternalRegion
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.PublicRegion != nil {
		toSerialize["public_region"] = o.PublicRegion
	}
	if o.Service != nil {
		toSerialize["service"] = o.Service
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Tenant != nil {
		toSerialize["tenant"] = o.Tenant
	}
	if o.Vendor != nil {
		toSerialize["vendor"] = o.Vendor
	}
	return json.Marshal(toSerialize)
}

type NullableCoreDescribeBucketResponse struct {
	value *CoreDescribeBucketResponse
	isSet bool
}

func (v NullableCoreDescribeBucketResponse) Get() *CoreDescribeBucketResponse {
	return v.value
}

func (v *NullableCoreDescribeBucketResponse) Set(val *CoreDescribeBucketResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreDescribeBucketResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreDescribeBucketResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreDescribeBucketResponse(val *CoreDescribeBucketResponse) *NullableCoreDescribeBucketResponse {
	return &NullableCoreDescribeBucketResponse{value: val, isSet: true}
}

func (v NullableCoreDescribeBucketResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreDescribeBucketResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


