/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreAddInstanceToResourcePoolRequest struct for CoreAddInstanceToResourcePoolRequest
type CoreAddInstanceToResourcePoolRequest struct {
	Hosts *[]string `json:"hosts,omitempty"`
	Instances *[]string `json:"instances,omitempty"`
	RootPassword *string `json:"root_password,omitempty"`
}

// NewCoreAddInstanceToResourcePoolRequest instantiates a new CoreAddInstanceToResourcePoolRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreAddInstanceToResourcePoolRequest() *CoreAddInstanceToResourcePoolRequest {
	this := CoreAddInstanceToResourcePoolRequest{}
	return &this
}

// NewCoreAddInstanceToResourcePoolRequestWithDefaults instantiates a new CoreAddInstanceToResourcePoolRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreAddInstanceToResourcePoolRequestWithDefaults() *CoreAddInstanceToResourcePoolRequest {
	this := CoreAddInstanceToResourcePoolRequest{}
	return &this
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *CoreAddInstanceToResourcePoolRequest) GetHosts() []string {
	if o == nil || o.Hosts == nil {
		var ret []string
		return ret
	}
	return *o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreAddInstanceToResourcePoolRequest) GetHostsOk() (*[]string, bool) {
	if o == nil || o.Hosts == nil {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *CoreAddInstanceToResourcePoolRequest) HasHosts() bool {
	if o != nil && o.Hosts != nil {
		return true
	}

	return false
}

// SetHosts gets a reference to the given []string and assigns it to the Hosts field.
func (o *CoreAddInstanceToResourcePoolRequest) SetHosts(v []string) {
	o.Hosts = &v
}

// GetInstances returns the Instances field value if set, zero value otherwise.
func (o *CoreAddInstanceToResourcePoolRequest) GetInstances() []string {
	if o == nil || o.Instances == nil {
		var ret []string
		return ret
	}
	return *o.Instances
}

// GetInstancesOk returns a tuple with the Instances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreAddInstanceToResourcePoolRequest) GetInstancesOk() (*[]string, bool) {
	if o == nil || o.Instances == nil {
		return nil, false
	}
	return o.Instances, true
}

// HasInstances returns a boolean if a field has been set.
func (o *CoreAddInstanceToResourcePoolRequest) HasInstances() bool {
	if o != nil && o.Instances != nil {
		return true
	}

	return false
}

// SetInstances gets a reference to the given []string and assigns it to the Instances field.
func (o *CoreAddInstanceToResourcePoolRequest) SetInstances(v []string) {
	o.Instances = &v
}

// GetRootPassword returns the RootPassword field value if set, zero value otherwise.
func (o *CoreAddInstanceToResourcePoolRequest) GetRootPassword() string {
	if o == nil || o.RootPassword == nil {
		var ret string
		return ret
	}
	return *o.RootPassword
}

// GetRootPasswordOk returns a tuple with the RootPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreAddInstanceToResourcePoolRequest) GetRootPasswordOk() (*string, bool) {
	if o == nil || o.RootPassword == nil {
		return nil, false
	}
	return o.RootPassword, true
}

// HasRootPassword returns a boolean if a field has been set.
func (o *CoreAddInstanceToResourcePoolRequest) HasRootPassword() bool {
	if o != nil && o.RootPassword != nil {
		return true
	}

	return false
}

// SetRootPassword gets a reference to the given string and assigns it to the RootPassword field.
func (o *CoreAddInstanceToResourcePoolRequest) SetRootPassword(v string) {
	o.RootPassword = &v
}

func (o CoreAddInstanceToResourcePoolRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Hosts != nil {
		toSerialize["hosts"] = o.Hosts
	}
	if o.Instances != nil {
		toSerialize["instances"] = o.Instances
	}
	if o.RootPassword != nil {
		toSerialize["root_password"] = o.RootPassword
	}
	return json.Marshal(toSerialize)
}

type NullableCoreAddInstanceToResourcePoolRequest struct {
	value *CoreAddInstanceToResourcePoolRequest
	isSet bool
}

func (v NullableCoreAddInstanceToResourcePoolRequest) Get() *CoreAddInstanceToResourcePoolRequest {
	return v.value
}

func (v *NullableCoreAddInstanceToResourcePoolRequest) Set(val *CoreAddInstanceToResourcePoolRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreAddInstanceToResourcePoolRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreAddInstanceToResourcePoolRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreAddInstanceToResourcePoolRequest(val *CoreAddInstanceToResourcePoolRequest) *NullableCoreAddInstanceToResourcePoolRequest {
	return &NullableCoreAddInstanceToResourcePoolRequest{value: val, isSet: true}
}

func (v NullableCoreAddInstanceToResourcePoolRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreAddInstanceToResourcePoolRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


