/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// OpsModifySilenceRequest struct for OpsModifySilenceRequest
type OpsModifySilenceRequest struct {
	Comment *string `json:"comment,omitempty"`
	EndAt *string `json:"end_at,omitempty"`
	Id *string `json:"id,omitempty"`
	Matcher *[]OpsMatcher `json:"matcher,omitempty"`
	StartAt *string `json:"start_at,omitempty"`
}

// NewOpsModifySilenceRequest instantiates a new OpsModifySilenceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsModifySilenceRequest() *OpsModifySilenceRequest {
	this := OpsModifySilenceRequest{}
	return &this
}

// NewOpsModifySilenceRequestWithDefaults instantiates a new OpsModifySilenceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsModifySilenceRequestWithDefaults() *OpsModifySilenceRequest {
	this := OpsModifySilenceRequest{}
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *OpsModifySilenceRequest) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsModifySilenceRequest) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *OpsModifySilenceRequest) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *OpsModifySilenceRequest) SetComment(v string) {
	o.Comment = &v
}

// GetEndAt returns the EndAt field value if set, zero value otherwise.
func (o *OpsModifySilenceRequest) GetEndAt() string {
	if o == nil || o.EndAt == nil {
		var ret string
		return ret
	}
	return *o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsModifySilenceRequest) GetEndAtOk() (*string, bool) {
	if o == nil || o.EndAt == nil {
		return nil, false
	}
	return o.EndAt, true
}

// HasEndAt returns a boolean if a field has been set.
func (o *OpsModifySilenceRequest) HasEndAt() bool {
	if o != nil && o.EndAt != nil {
		return true
	}

	return false
}

// SetEndAt gets a reference to the given string and assigns it to the EndAt field.
func (o *OpsModifySilenceRequest) SetEndAt(v string) {
	o.EndAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OpsModifySilenceRequest) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsModifySilenceRequest) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OpsModifySilenceRequest) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OpsModifySilenceRequest) SetId(v string) {
	o.Id = &v
}

// GetMatcher returns the Matcher field value if set, zero value otherwise.
func (o *OpsModifySilenceRequest) GetMatcher() []OpsMatcher {
	if o == nil || o.Matcher == nil {
		var ret []OpsMatcher
		return ret
	}
	return *o.Matcher
}

// GetMatcherOk returns a tuple with the Matcher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsModifySilenceRequest) GetMatcherOk() (*[]OpsMatcher, bool) {
	if o == nil || o.Matcher == nil {
		return nil, false
	}
	return o.Matcher, true
}

// HasMatcher returns a boolean if a field has been set.
func (o *OpsModifySilenceRequest) HasMatcher() bool {
	if o != nil && o.Matcher != nil {
		return true
	}

	return false
}

// SetMatcher gets a reference to the given []OpsMatcher and assigns it to the Matcher field.
func (o *OpsModifySilenceRequest) SetMatcher(v []OpsMatcher) {
	o.Matcher = &v
}

// GetStartAt returns the StartAt field value if set, zero value otherwise.
func (o *OpsModifySilenceRequest) GetStartAt() string {
	if o == nil || o.StartAt == nil {
		var ret string
		return ret
	}
	return *o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsModifySilenceRequest) GetStartAtOk() (*string, bool) {
	if o == nil || o.StartAt == nil {
		return nil, false
	}
	return o.StartAt, true
}

// HasStartAt returns a boolean if a field has been set.
func (o *OpsModifySilenceRequest) HasStartAt() bool {
	if o != nil && o.StartAt != nil {
		return true
	}

	return false
}

// SetStartAt gets a reference to the given string and assigns it to the StartAt field.
func (o *OpsModifySilenceRequest) SetStartAt(v string) {
	o.StartAt = &v
}

func (o OpsModifySilenceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.EndAt != nil {
		toSerialize["end_at"] = o.EndAt
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Matcher != nil {
		toSerialize["matcher"] = o.Matcher
	}
	if o.StartAt != nil {
		toSerialize["start_at"] = o.StartAt
	}
	return json.Marshal(toSerialize)
}

type NullableOpsModifySilenceRequest struct {
	value *OpsModifySilenceRequest
	isSet bool
}

func (v NullableOpsModifySilenceRequest) Get() *OpsModifySilenceRequest {
	return v.value
}

func (v *NullableOpsModifySilenceRequest) Set(val *OpsModifySilenceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsModifySilenceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsModifySilenceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsModifySilenceRequest(val *OpsModifySilenceRequest) *NullableOpsModifySilenceRequest {
	return &NullableOpsModifySilenceRequest{value: val, isSet: true}
}

func (v NullableOpsModifySilenceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsModifySilenceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


