/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// AccountComplementExternalUserAndTenantRequest struct for AccountComplementExternalUserAndTenantRequest
type AccountComplementExternalUserAndTenantRequest struct {
	Tenant *AccountModifyExternalTenantRequest `json:"tenant,omitempty"`
	User *AccountModifyExternalUserRequest `json:"user,omitempty"`
}

// NewAccountComplementExternalUserAndTenantRequest instantiates a new AccountComplementExternalUserAndTenantRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountComplementExternalUserAndTenantRequest() *AccountComplementExternalUserAndTenantRequest {
	this := AccountComplementExternalUserAndTenantRequest{}
	return &this
}

// NewAccountComplementExternalUserAndTenantRequestWithDefaults instantiates a new AccountComplementExternalUserAndTenantRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountComplementExternalUserAndTenantRequestWithDefaults() *AccountComplementExternalUserAndTenantRequest {
	this := AccountComplementExternalUserAndTenantRequest{}
	return &this
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *AccountComplementExternalUserAndTenantRequest) GetTenant() AccountModifyExternalTenantRequest {
	if o == nil || o.Tenant == nil {
		var ret AccountModifyExternalTenantRequest
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountComplementExternalUserAndTenantRequest) GetTenantOk() (*AccountModifyExternalTenantRequest, bool) {
	if o == nil || o.Tenant == nil {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *AccountComplementExternalUserAndTenantRequest) HasTenant() bool {
	if o != nil && o.Tenant != nil {
		return true
	}

	return false
}

// SetTenant gets a reference to the given AccountModifyExternalTenantRequest and assigns it to the Tenant field.
func (o *AccountComplementExternalUserAndTenantRequest) SetTenant(v AccountModifyExternalTenantRequest) {
	o.Tenant = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *AccountComplementExternalUserAndTenantRequest) GetUser() AccountModifyExternalUserRequest {
	if o == nil || o.User == nil {
		var ret AccountModifyExternalUserRequest
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountComplementExternalUserAndTenantRequest) GetUserOk() (*AccountModifyExternalUserRequest, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *AccountComplementExternalUserAndTenantRequest) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given AccountModifyExternalUserRequest and assigns it to the User field.
func (o *AccountComplementExternalUserAndTenantRequest) SetUser(v AccountModifyExternalUserRequest) {
	o.User = &v
}

func (o AccountComplementExternalUserAndTenantRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Tenant != nil {
		toSerialize["tenant"] = o.Tenant
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	return json.Marshal(toSerialize)
}

type NullableAccountComplementExternalUserAndTenantRequest struct {
	value *AccountComplementExternalUserAndTenantRequest
	isSet bool
}

func (v NullableAccountComplementExternalUserAndTenantRequest) Get() *AccountComplementExternalUserAndTenantRequest {
	return v.value
}

func (v *NullableAccountComplementExternalUserAndTenantRequest) Set(val *AccountComplementExternalUserAndTenantRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountComplementExternalUserAndTenantRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountComplementExternalUserAndTenantRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountComplementExternalUserAndTenantRequest(val *AccountComplementExternalUserAndTenantRequest) *NullableAccountComplementExternalUserAndTenantRequest {
	return &NullableAccountComplementExternalUserAndTenantRequest{value: val, isSet: true}
}

func (v NullableAccountComplementExternalUserAndTenantRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountComplementExternalUserAndTenantRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


