/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// OpsAddCommentResponse struct for OpsAddCommentResponse
type OpsAddCommentResponse struct {
	Content *string `json:"content,omitempty"`
	Id *string `json:"id,omitempty"`
	Sender *string `json:"sender,omitempty"`
	Ticket *string `json:"ticket,omitempty"`
}

// NewOpsAddCommentResponse instantiates a new OpsAddCommentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsAddCommentResponse() *OpsAddCommentResponse {
	this := OpsAddCommentResponse{}
	return &this
}

// NewOpsAddCommentResponseWithDefaults instantiates a new OpsAddCommentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsAddCommentResponseWithDefaults() *OpsAddCommentResponse {
	this := OpsAddCommentResponse{}
	return &this
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *OpsAddCommentResponse) GetContent() string {
	if o == nil || o.Content == nil {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsAddCommentResponse) GetContentOk() (*string, bool) {
	if o == nil || o.Content == nil {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *OpsAddCommentResponse) HasContent() bool {
	if o != nil && o.Content != nil {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *OpsAddCommentResponse) SetContent(v string) {
	o.Content = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OpsAddCommentResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsAddCommentResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OpsAddCommentResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OpsAddCommentResponse) SetId(v string) {
	o.Id = &v
}

// GetSender returns the Sender field value if set, zero value otherwise.
func (o *OpsAddCommentResponse) GetSender() string {
	if o == nil || o.Sender == nil {
		var ret string
		return ret
	}
	return *o.Sender
}

// GetSenderOk returns a tuple with the Sender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsAddCommentResponse) GetSenderOk() (*string, bool) {
	if o == nil || o.Sender == nil {
		return nil, false
	}
	return o.Sender, true
}

// HasSender returns a boolean if a field has been set.
func (o *OpsAddCommentResponse) HasSender() bool {
	if o != nil && o.Sender != nil {
		return true
	}

	return false
}

// SetSender gets a reference to the given string and assigns it to the Sender field.
func (o *OpsAddCommentResponse) SetSender(v string) {
	o.Sender = &v
}

// GetTicket returns the Ticket field value if set, zero value otherwise.
func (o *OpsAddCommentResponse) GetTicket() string {
	if o == nil || o.Ticket == nil {
		var ret string
		return ret
	}
	return *o.Ticket
}

// GetTicketOk returns a tuple with the Ticket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsAddCommentResponse) GetTicketOk() (*string, bool) {
	if o == nil || o.Ticket == nil {
		return nil, false
	}
	return o.Ticket, true
}

// HasTicket returns a boolean if a field has been set.
func (o *OpsAddCommentResponse) HasTicket() bool {
	if o != nil && o.Ticket != nil {
		return true
	}

	return false
}

// SetTicket gets a reference to the given string and assigns it to the Ticket field.
func (o *OpsAddCommentResponse) SetTicket(v string) {
	o.Ticket = &v
}

func (o OpsAddCommentResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Content != nil {
		toSerialize["content"] = o.Content
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Sender != nil {
		toSerialize["sender"] = o.Sender
	}
	if o.Ticket != nil {
		toSerialize["ticket"] = o.Ticket
	}
	return json.Marshal(toSerialize)
}

type NullableOpsAddCommentResponse struct {
	value *OpsAddCommentResponse
	isSet bool
}

func (v NullableOpsAddCommentResponse) Get() *OpsAddCommentResponse {
	return v.value
}

func (v *NullableOpsAddCommentResponse) Set(val *OpsAddCommentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsAddCommentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsAddCommentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsAddCommentResponse(val *OpsAddCommentResponse) *NullableOpsAddCommentResponse {
	return &NullableOpsAddCommentResponse{value: val, isSet: true}
}

func (v NullableOpsAddCommentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsAddCommentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


