/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreCreateResourcePoolRequest struct for CoreCreateResourcePoolRequest
type CoreCreateResourcePoolRequest struct {
	DefaultOssZone *string `json:"default_oss_zone,omitempty"`
	Description *string `json:"description,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	OssConnectivity *[]string `json:"oss_connectivity,omitempty"`
	Tenant *string `json:"tenant,omitempty"`
}

// NewCoreCreateResourcePoolRequest instantiates a new CoreCreateResourcePoolRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreCreateResourcePoolRequest() *CoreCreateResourcePoolRequest {
	this := CoreCreateResourcePoolRequest{}
	return &this
}

// NewCoreCreateResourcePoolRequestWithDefaults instantiates a new CoreCreateResourcePoolRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreCreateResourcePoolRequestWithDefaults() *CoreCreateResourcePoolRequest {
	this := CoreCreateResourcePoolRequest{}
	return &this
}

// GetDefaultOssZone returns the DefaultOssZone field value if set, zero value otherwise.
func (o *CoreCreateResourcePoolRequest) GetDefaultOssZone() string {
	if o == nil || o.DefaultOssZone == nil {
		var ret string
		return ret
	}
	return *o.DefaultOssZone
}

// GetDefaultOssZoneOk returns a tuple with the DefaultOssZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateResourcePoolRequest) GetDefaultOssZoneOk() (*string, bool) {
	if o == nil || o.DefaultOssZone == nil {
		return nil, false
	}
	return o.DefaultOssZone, true
}

// HasDefaultOssZone returns a boolean if a field has been set.
func (o *CoreCreateResourcePoolRequest) HasDefaultOssZone() bool {
	if o != nil && o.DefaultOssZone != nil {
		return true
	}

	return false
}

// SetDefaultOssZone gets a reference to the given string and assigns it to the DefaultOssZone field.
func (o *CoreCreateResourcePoolRequest) SetDefaultOssZone(v string) {
	o.DefaultOssZone = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CoreCreateResourcePoolRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateResourcePoolRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CoreCreateResourcePoolRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CoreCreateResourcePoolRequest) SetDescription(v string) {
	o.Description = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *CoreCreateResourcePoolRequest) GetDisplayName() string {
	if o == nil || o.DisplayName == nil {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateResourcePoolRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || o.DisplayName == nil {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *CoreCreateResourcePoolRequest) HasDisplayName() bool {
	if o != nil && o.DisplayName != nil {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *CoreCreateResourcePoolRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetOssConnectivity returns the OssConnectivity field value if set, zero value otherwise.
func (o *CoreCreateResourcePoolRequest) GetOssConnectivity() []string {
	if o == nil || o.OssConnectivity == nil {
		var ret []string
		return ret
	}
	return *o.OssConnectivity
}

// GetOssConnectivityOk returns a tuple with the OssConnectivity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateResourcePoolRequest) GetOssConnectivityOk() (*[]string, bool) {
	if o == nil || o.OssConnectivity == nil {
		return nil, false
	}
	return o.OssConnectivity, true
}

// HasOssConnectivity returns a boolean if a field has been set.
func (o *CoreCreateResourcePoolRequest) HasOssConnectivity() bool {
	if o != nil && o.OssConnectivity != nil {
		return true
	}

	return false
}

// SetOssConnectivity gets a reference to the given []string and assigns it to the OssConnectivity field.
func (o *CoreCreateResourcePoolRequest) SetOssConnectivity(v []string) {
	o.OssConnectivity = &v
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *CoreCreateResourcePoolRequest) GetTenant() string {
	if o == nil || o.Tenant == nil {
		var ret string
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateResourcePoolRequest) GetTenantOk() (*string, bool) {
	if o == nil || o.Tenant == nil {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *CoreCreateResourcePoolRequest) HasTenant() bool {
	if o != nil && o.Tenant != nil {
		return true
	}

	return false
}

// SetTenant gets a reference to the given string and assigns it to the Tenant field.
func (o *CoreCreateResourcePoolRequest) SetTenant(v string) {
	o.Tenant = &v
}

func (o CoreCreateResourcePoolRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.DefaultOssZone != nil {
		toSerialize["default_oss_zone"] = o.DefaultOssZone
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.DisplayName != nil {
		toSerialize["display_name"] = o.DisplayName
	}
	if o.OssConnectivity != nil {
		toSerialize["oss_connectivity"] = o.OssConnectivity
	}
	if o.Tenant != nil {
		toSerialize["tenant"] = o.Tenant
	}
	return json.Marshal(toSerialize)
}

type NullableCoreCreateResourcePoolRequest struct {
	value *CoreCreateResourcePoolRequest
	isSet bool
}

func (v NullableCoreCreateResourcePoolRequest) Get() *CoreCreateResourcePoolRequest {
	return v.value
}

func (v *NullableCoreCreateResourcePoolRequest) Set(val *CoreCreateResourcePoolRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreCreateResourcePoolRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreCreateResourcePoolRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreCreateResourcePoolRequest(val *CoreCreateResourcePoolRequest) *NullableCoreCreateResourcePoolRequest {
	return &NullableCoreCreateResourcePoolRequest{value: val, isSet: true}
}

func (v NullableCoreCreateResourcePoolRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreCreateResourcePoolRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


