/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreDescribeQuotaResponse struct for CoreDescribeQuotaResponse
type CoreDescribeQuotaResponse struct {
	Quota *int32 `json:"quota,omitempty"`
	Tenant *string `json:"tenant,omitempty"`
	Type *string `json:"type,omitempty"`
	Usage *string `json:"usage,omitempty"`
	Zone *string `json:"zone,omitempty"`
}

// NewCoreDescribeQuotaResponse instantiates a new CoreDescribeQuotaResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreDescribeQuotaResponse() *CoreDescribeQuotaResponse {
	this := CoreDescribeQuotaResponse{}
	return &this
}

// NewCoreDescribeQuotaResponseWithDefaults instantiates a new CoreDescribeQuotaResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreDescribeQuotaResponseWithDefaults() *CoreDescribeQuotaResponse {
	this := CoreDescribeQuotaResponse{}
	return &this
}

// GetQuota returns the Quota field value if set, zero value otherwise.
func (o *CoreDescribeQuotaResponse) GetQuota() int32 {
	if o == nil || o.Quota == nil {
		var ret int32
		return ret
	}
	return *o.Quota
}

// GetQuotaOk returns a tuple with the Quota field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeQuotaResponse) GetQuotaOk() (*int32, bool) {
	if o == nil || o.Quota == nil {
		return nil, false
	}
	return o.Quota, true
}

// HasQuota returns a boolean if a field has been set.
func (o *CoreDescribeQuotaResponse) HasQuota() bool {
	if o != nil && o.Quota != nil {
		return true
	}

	return false
}

// SetQuota gets a reference to the given int32 and assigns it to the Quota field.
func (o *CoreDescribeQuotaResponse) SetQuota(v int32) {
	o.Quota = &v
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *CoreDescribeQuotaResponse) GetTenant() string {
	if o == nil || o.Tenant == nil {
		var ret string
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeQuotaResponse) GetTenantOk() (*string, bool) {
	if o == nil || o.Tenant == nil {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *CoreDescribeQuotaResponse) HasTenant() bool {
	if o != nil && o.Tenant != nil {
		return true
	}

	return false
}

// SetTenant gets a reference to the given string and assigns it to the Tenant field.
func (o *CoreDescribeQuotaResponse) SetTenant(v string) {
	o.Tenant = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CoreDescribeQuotaResponse) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeQuotaResponse) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CoreDescribeQuotaResponse) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CoreDescribeQuotaResponse) SetType(v string) {
	o.Type = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *CoreDescribeQuotaResponse) GetUsage() string {
	if o == nil || o.Usage == nil {
		var ret string
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeQuotaResponse) GetUsageOk() (*string, bool) {
	if o == nil || o.Usage == nil {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *CoreDescribeQuotaResponse) HasUsage() bool {
	if o != nil && o.Usage != nil {
		return true
	}

	return false
}

// SetUsage gets a reference to the given string and assigns it to the Usage field.
func (o *CoreDescribeQuotaResponse) SetUsage(v string) {
	o.Usage = &v
}

// GetZone returns the Zone field value if set, zero value otherwise.
func (o *CoreDescribeQuotaResponse) GetZone() string {
	if o == nil || o.Zone == nil {
		var ret string
		return ret
	}
	return *o.Zone
}

// GetZoneOk returns a tuple with the Zone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeQuotaResponse) GetZoneOk() (*string, bool) {
	if o == nil || o.Zone == nil {
		return nil, false
	}
	return o.Zone, true
}

// HasZone returns a boolean if a field has been set.
func (o *CoreDescribeQuotaResponse) HasZone() bool {
	if o != nil && o.Zone != nil {
		return true
	}

	return false
}

// SetZone gets a reference to the given string and assigns it to the Zone field.
func (o *CoreDescribeQuotaResponse) SetZone(v string) {
	o.Zone = &v
}

func (o CoreDescribeQuotaResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Quota != nil {
		toSerialize["quota"] = o.Quota
	}
	if o.Tenant != nil {
		toSerialize["tenant"] = o.Tenant
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if o.Usage != nil {
		toSerialize["usage"] = o.Usage
	}
	if o.Zone != nil {
		toSerialize["zone"] = o.Zone
	}
	return json.Marshal(toSerialize)
}

type NullableCoreDescribeQuotaResponse struct {
	value *CoreDescribeQuotaResponse
	isSet bool
}

func (v NullableCoreDescribeQuotaResponse) Get() *CoreDescribeQuotaResponse {
	return v.value
}

func (v *NullableCoreDescribeQuotaResponse) Set(val *CoreDescribeQuotaResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreDescribeQuotaResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreDescribeQuotaResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreDescribeQuotaResponse(val *CoreDescribeQuotaResponse) *NullableCoreDescribeQuotaResponse {
	return &NullableCoreDescribeQuotaResponse{value: val, isSet: true}
}

func (v NullableCoreDescribeQuotaResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreDescribeQuotaResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


