/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreCreateUnmanagedServiceRequest struct for CoreCreateUnmanagedServiceRequest
type CoreCreateUnmanagedServiceRequest struct {
	Description *string `json:"description,omitempty"`
	Extra *CoreCreateServiceIaasExtraRequest `json:"extra,omitempty"`
	Iaas *CloudmgrcoreIaasResource `json:"iaas,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewCoreCreateUnmanagedServiceRequest instantiates a new CoreCreateUnmanagedServiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreCreateUnmanagedServiceRequest() *CoreCreateUnmanagedServiceRequest {
	this := CoreCreateUnmanagedServiceRequest{}
	return &this
}

// NewCoreCreateUnmanagedServiceRequestWithDefaults instantiates a new CoreCreateUnmanagedServiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreCreateUnmanagedServiceRequestWithDefaults() *CoreCreateUnmanagedServiceRequest {
	this := CoreCreateUnmanagedServiceRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CoreCreateUnmanagedServiceRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateUnmanagedServiceRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CoreCreateUnmanagedServiceRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CoreCreateUnmanagedServiceRequest) SetDescription(v string) {
	o.Description = &v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *CoreCreateUnmanagedServiceRequest) GetExtra() CoreCreateServiceIaasExtraRequest {
	if o == nil || o.Extra == nil {
		var ret CoreCreateServiceIaasExtraRequest
		return ret
	}
	return *o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateUnmanagedServiceRequest) GetExtraOk() (*CoreCreateServiceIaasExtraRequest, bool) {
	if o == nil || o.Extra == nil {
		return nil, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *CoreCreateUnmanagedServiceRequest) HasExtra() bool {
	if o != nil && o.Extra != nil {
		return true
	}

	return false
}

// SetExtra gets a reference to the given CoreCreateServiceIaasExtraRequest and assigns it to the Extra field.
func (o *CoreCreateUnmanagedServiceRequest) SetExtra(v CoreCreateServiceIaasExtraRequest) {
	o.Extra = &v
}

// GetIaas returns the Iaas field value if set, zero value otherwise.
func (o *CoreCreateUnmanagedServiceRequest) GetIaas() CloudmgrcoreIaasResource {
	if o == nil || o.Iaas == nil {
		var ret CloudmgrcoreIaasResource
		return ret
	}
	return *o.Iaas
}

// GetIaasOk returns a tuple with the Iaas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateUnmanagedServiceRequest) GetIaasOk() (*CloudmgrcoreIaasResource, bool) {
	if o == nil || o.Iaas == nil {
		return nil, false
	}
	return o.Iaas, true
}

// HasIaas returns a boolean if a field has been set.
func (o *CoreCreateUnmanagedServiceRequest) HasIaas() bool {
	if o != nil && o.Iaas != nil {
		return true
	}

	return false
}

// SetIaas gets a reference to the given CloudmgrcoreIaasResource and assigns it to the Iaas field.
func (o *CoreCreateUnmanagedServiceRequest) SetIaas(v CloudmgrcoreIaasResource) {
	o.Iaas = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CoreCreateUnmanagedServiceRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateUnmanagedServiceRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CoreCreateUnmanagedServiceRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CoreCreateUnmanagedServiceRequest) SetName(v string) {
	o.Name = &v
}

func (o CoreCreateUnmanagedServiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Extra != nil {
		toSerialize["extra"] = o.Extra
	}
	if o.Iaas != nil {
		toSerialize["iaas"] = o.Iaas
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableCoreCreateUnmanagedServiceRequest struct {
	value *CoreCreateUnmanagedServiceRequest
	isSet bool
}

func (v NullableCoreCreateUnmanagedServiceRequest) Get() *CoreCreateUnmanagedServiceRequest {
	return v.value
}

func (v *NullableCoreCreateUnmanagedServiceRequest) Set(val *CoreCreateUnmanagedServiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreCreateUnmanagedServiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreCreateUnmanagedServiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreCreateUnmanagedServiceRequest(val *CoreCreateUnmanagedServiceRequest) *NullableCoreCreateUnmanagedServiceRequest {
	return &NullableCoreCreateUnmanagedServiceRequest{value: val, isSet: true}
}

func (v NullableCoreCreateUnmanagedServiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreCreateUnmanagedServiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


