/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// OpsDescribeSilenceResponse struct for OpsDescribeSilenceResponse
type OpsDescribeSilenceResponse struct {
	Comment *string `json:"comment,omitempty"`
	CreateBy *string `json:"create_by,omitempty"`
	EndAt *string `json:"end_at,omitempty"`
	Id *string `json:"id,omitempty"`
	Matcher *[]OpsMatcher `json:"matcher,omitempty"`
	StartAt *string `json:"start_at,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewOpsDescribeSilenceResponse instantiates a new OpsDescribeSilenceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsDescribeSilenceResponse() *OpsDescribeSilenceResponse {
	this := OpsDescribeSilenceResponse{}
	return &this
}

// NewOpsDescribeSilenceResponseWithDefaults instantiates a new OpsDescribeSilenceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsDescribeSilenceResponseWithDefaults() *OpsDescribeSilenceResponse {
	this := OpsDescribeSilenceResponse{}
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *OpsDescribeSilenceResponse) GetComment() string {
	if o == nil || o.Comment == nil {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeSilenceResponse) GetCommentOk() (*string, bool) {
	if o == nil || o.Comment == nil {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *OpsDescribeSilenceResponse) HasComment() bool {
	if o != nil && o.Comment != nil {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *OpsDescribeSilenceResponse) SetComment(v string) {
	o.Comment = &v
}

// GetCreateBy returns the CreateBy field value if set, zero value otherwise.
func (o *OpsDescribeSilenceResponse) GetCreateBy() string {
	if o == nil || o.CreateBy == nil {
		var ret string
		return ret
	}
	return *o.CreateBy
}

// GetCreateByOk returns a tuple with the CreateBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeSilenceResponse) GetCreateByOk() (*string, bool) {
	if o == nil || o.CreateBy == nil {
		return nil, false
	}
	return o.CreateBy, true
}

// HasCreateBy returns a boolean if a field has been set.
func (o *OpsDescribeSilenceResponse) HasCreateBy() bool {
	if o != nil && o.CreateBy != nil {
		return true
	}

	return false
}

// SetCreateBy gets a reference to the given string and assigns it to the CreateBy field.
func (o *OpsDescribeSilenceResponse) SetCreateBy(v string) {
	o.CreateBy = &v
}

// GetEndAt returns the EndAt field value if set, zero value otherwise.
func (o *OpsDescribeSilenceResponse) GetEndAt() string {
	if o == nil || o.EndAt == nil {
		var ret string
		return ret
	}
	return *o.EndAt
}

// GetEndAtOk returns a tuple with the EndAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeSilenceResponse) GetEndAtOk() (*string, bool) {
	if o == nil || o.EndAt == nil {
		return nil, false
	}
	return o.EndAt, true
}

// HasEndAt returns a boolean if a field has been set.
func (o *OpsDescribeSilenceResponse) HasEndAt() bool {
	if o != nil && o.EndAt != nil {
		return true
	}

	return false
}

// SetEndAt gets a reference to the given string and assigns it to the EndAt field.
func (o *OpsDescribeSilenceResponse) SetEndAt(v string) {
	o.EndAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OpsDescribeSilenceResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeSilenceResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OpsDescribeSilenceResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OpsDescribeSilenceResponse) SetId(v string) {
	o.Id = &v
}

// GetMatcher returns the Matcher field value if set, zero value otherwise.
func (o *OpsDescribeSilenceResponse) GetMatcher() []OpsMatcher {
	if o == nil || o.Matcher == nil {
		var ret []OpsMatcher
		return ret
	}
	return *o.Matcher
}

// GetMatcherOk returns a tuple with the Matcher field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeSilenceResponse) GetMatcherOk() (*[]OpsMatcher, bool) {
	if o == nil || o.Matcher == nil {
		return nil, false
	}
	return o.Matcher, true
}

// HasMatcher returns a boolean if a field has been set.
func (o *OpsDescribeSilenceResponse) HasMatcher() bool {
	if o != nil && o.Matcher != nil {
		return true
	}

	return false
}

// SetMatcher gets a reference to the given []OpsMatcher and assigns it to the Matcher field.
func (o *OpsDescribeSilenceResponse) SetMatcher(v []OpsMatcher) {
	o.Matcher = &v
}

// GetStartAt returns the StartAt field value if set, zero value otherwise.
func (o *OpsDescribeSilenceResponse) GetStartAt() string {
	if o == nil || o.StartAt == nil {
		var ret string
		return ret
	}
	return *o.StartAt
}

// GetStartAtOk returns a tuple with the StartAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeSilenceResponse) GetStartAtOk() (*string, bool) {
	if o == nil || o.StartAt == nil {
		return nil, false
	}
	return o.StartAt, true
}

// HasStartAt returns a boolean if a field has been set.
func (o *OpsDescribeSilenceResponse) HasStartAt() bool {
	if o != nil && o.StartAt != nil {
		return true
	}

	return false
}

// SetStartAt gets a reference to the given string and assigns it to the StartAt field.
func (o *OpsDescribeSilenceResponse) SetStartAt(v string) {
	o.StartAt = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OpsDescribeSilenceResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeSilenceResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OpsDescribeSilenceResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *OpsDescribeSilenceResponse) SetStatus(v string) {
	o.Status = &v
}

func (o OpsDescribeSilenceResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Comment != nil {
		toSerialize["comment"] = o.Comment
	}
	if o.CreateBy != nil {
		toSerialize["create_by"] = o.CreateBy
	}
	if o.EndAt != nil {
		toSerialize["end_at"] = o.EndAt
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Matcher != nil {
		toSerialize["matcher"] = o.Matcher
	}
	if o.StartAt != nil {
		toSerialize["start_at"] = o.StartAt
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableOpsDescribeSilenceResponse struct {
	value *OpsDescribeSilenceResponse
	isSet bool
}

func (v NullableOpsDescribeSilenceResponse) Get() *OpsDescribeSilenceResponse {
	return v.value
}

func (v *NullableOpsDescribeSilenceResponse) Set(val *OpsDescribeSilenceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsDescribeSilenceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsDescribeSilenceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsDescribeSilenceResponse(val *OpsDescribeSilenceResponse) *NullableOpsDescribeSilenceResponse {
	return &NullableOpsDescribeSilenceResponse{value: val, isSet: true}
}

func (v NullableOpsDescribeSilenceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsDescribeSilenceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


