/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreDescribeRegionConfigResponse struct for CoreDescribeRegionConfigResponse
type CoreDescribeRegionConfigResponse struct {
	AccessKeyId *string `json:"access_key_id,omitempty"`
	AccessKeySecret *string `json:"access_key_secret,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	Id *string `json:"id,omitempty"`
	Project *string `json:"project,omitempty"`
	RecyclingSecurityGroup *string `json:"recycling_security_group,omitempty"`
	Region *string `json:"region,omitempty"`
	ReverseConnect *bool `json:"reverse_connect,omitempty"`
	Tenant *string `json:"tenant,omitempty"`
	Vendor *string `json:"vendor,omitempty"`
	VendorTenant *string `json:"vendor_tenant,omitempty"`
	Vpc *string `json:"vpc,omitempty"`
}

// NewCoreDescribeRegionConfigResponse instantiates a new CoreDescribeRegionConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreDescribeRegionConfigResponse() *CoreDescribeRegionConfigResponse {
	this := CoreDescribeRegionConfigResponse{}
	return &this
}

// NewCoreDescribeRegionConfigResponseWithDefaults instantiates a new CoreDescribeRegionConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreDescribeRegionConfigResponseWithDefaults() *CoreDescribeRegionConfigResponse {
	this := CoreDescribeRegionConfigResponse{}
	return &this
}

// GetAccessKeyId returns the AccessKeyId field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetAccessKeyId() string {
	if o == nil || o.AccessKeyId == nil {
		var ret string
		return ret
	}
	return *o.AccessKeyId
}

// GetAccessKeyIdOk returns a tuple with the AccessKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetAccessKeyIdOk() (*string, bool) {
	if o == nil || o.AccessKeyId == nil {
		return nil, false
	}
	return o.AccessKeyId, true
}

// HasAccessKeyId returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasAccessKeyId() bool {
	if o != nil && o.AccessKeyId != nil {
		return true
	}

	return false
}

// SetAccessKeyId gets a reference to the given string and assigns it to the AccessKeyId field.
func (o *CoreDescribeRegionConfigResponse) SetAccessKeyId(v string) {
	o.AccessKeyId = &v
}

// GetAccessKeySecret returns the AccessKeySecret field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetAccessKeySecret() string {
	if o == nil || o.AccessKeySecret == nil {
		var ret string
		return ret
	}
	return *o.AccessKeySecret
}

// GetAccessKeySecretOk returns a tuple with the AccessKeySecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetAccessKeySecretOk() (*string, bool) {
	if o == nil || o.AccessKeySecret == nil {
		return nil, false
	}
	return o.AccessKeySecret, true
}

// HasAccessKeySecret returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasAccessKeySecret() bool {
	if o != nil && o.AccessKeySecret != nil {
		return true
	}

	return false
}

// SetAccessKeySecret gets a reference to the given string and assigns it to the AccessKeySecret field.
func (o *CoreDescribeRegionConfigResponse) SetAccessKeySecret(v string) {
	o.AccessKeySecret = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *CoreDescribeRegionConfigResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CoreDescribeRegionConfigResponse) SetId(v string) {
	o.Id = &v
}

// GetProject returns the Project field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetProject() string {
	if o == nil || o.Project == nil {
		var ret string
		return ret
	}
	return *o.Project
}

// GetProjectOk returns a tuple with the Project field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetProjectOk() (*string, bool) {
	if o == nil || o.Project == nil {
		return nil, false
	}
	return o.Project, true
}

// HasProject returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasProject() bool {
	if o != nil && o.Project != nil {
		return true
	}

	return false
}

// SetProject gets a reference to the given string and assigns it to the Project field.
func (o *CoreDescribeRegionConfigResponse) SetProject(v string) {
	o.Project = &v
}

// GetRecyclingSecurityGroup returns the RecyclingSecurityGroup field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetRecyclingSecurityGroup() string {
	if o == nil || o.RecyclingSecurityGroup == nil {
		var ret string
		return ret
	}
	return *o.RecyclingSecurityGroup
}

// GetRecyclingSecurityGroupOk returns a tuple with the RecyclingSecurityGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetRecyclingSecurityGroupOk() (*string, bool) {
	if o == nil || o.RecyclingSecurityGroup == nil {
		return nil, false
	}
	return o.RecyclingSecurityGroup, true
}

// HasRecyclingSecurityGroup returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasRecyclingSecurityGroup() bool {
	if o != nil && o.RecyclingSecurityGroup != nil {
		return true
	}

	return false
}

// SetRecyclingSecurityGroup gets a reference to the given string and assigns it to the RecyclingSecurityGroup field.
func (o *CoreDescribeRegionConfigResponse) SetRecyclingSecurityGroup(v string) {
	o.RecyclingSecurityGroup = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetRegion() string {
	if o == nil || o.Region == nil {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetRegionOk() (*string, bool) {
	if o == nil || o.Region == nil {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasRegion() bool {
	if o != nil && o.Region != nil {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *CoreDescribeRegionConfigResponse) SetRegion(v string) {
	o.Region = &v
}

// GetReverseConnect returns the ReverseConnect field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetReverseConnect() bool {
	if o == nil || o.ReverseConnect == nil {
		var ret bool
		return ret
	}
	return *o.ReverseConnect
}

// GetReverseConnectOk returns a tuple with the ReverseConnect field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetReverseConnectOk() (*bool, bool) {
	if o == nil || o.ReverseConnect == nil {
		return nil, false
	}
	return o.ReverseConnect, true
}

// HasReverseConnect returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasReverseConnect() bool {
	if o != nil && o.ReverseConnect != nil {
		return true
	}

	return false
}

// SetReverseConnect gets a reference to the given bool and assigns it to the ReverseConnect field.
func (o *CoreDescribeRegionConfigResponse) SetReverseConnect(v bool) {
	o.ReverseConnect = &v
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetTenant() string {
	if o == nil || o.Tenant == nil {
		var ret string
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetTenantOk() (*string, bool) {
	if o == nil || o.Tenant == nil {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasTenant() bool {
	if o != nil && o.Tenant != nil {
		return true
	}

	return false
}

// SetTenant gets a reference to the given string and assigns it to the Tenant field.
func (o *CoreDescribeRegionConfigResponse) SetTenant(v string) {
	o.Tenant = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetVendor() string {
	if o == nil || o.Vendor == nil {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetVendorOk() (*string, bool) {
	if o == nil || o.Vendor == nil {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasVendor() bool {
	if o != nil && o.Vendor != nil {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *CoreDescribeRegionConfigResponse) SetVendor(v string) {
	o.Vendor = &v
}

// GetVendorTenant returns the VendorTenant field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetVendorTenant() string {
	if o == nil || o.VendorTenant == nil {
		var ret string
		return ret
	}
	return *o.VendorTenant
}

// GetVendorTenantOk returns a tuple with the VendorTenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetVendorTenantOk() (*string, bool) {
	if o == nil || o.VendorTenant == nil {
		return nil, false
	}
	return o.VendorTenant, true
}

// HasVendorTenant returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasVendorTenant() bool {
	if o != nil && o.VendorTenant != nil {
		return true
	}

	return false
}

// SetVendorTenant gets a reference to the given string and assigns it to the VendorTenant field.
func (o *CoreDescribeRegionConfigResponse) SetVendorTenant(v string) {
	o.VendorTenant = &v
}

// GetVpc returns the Vpc field value if set, zero value otherwise.
func (o *CoreDescribeRegionConfigResponse) GetVpc() string {
	if o == nil || o.Vpc == nil {
		var ret string
		return ret
	}
	return *o.Vpc
}

// GetVpcOk returns a tuple with the Vpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeRegionConfigResponse) GetVpcOk() (*string, bool) {
	if o == nil || o.Vpc == nil {
		return nil, false
	}
	return o.Vpc, true
}

// HasVpc returns a boolean if a field has been set.
func (o *CoreDescribeRegionConfigResponse) HasVpc() bool {
	if o != nil && o.Vpc != nil {
		return true
	}

	return false
}

// SetVpc gets a reference to the given string and assigns it to the Vpc field.
func (o *CoreDescribeRegionConfigResponse) SetVpc(v string) {
	o.Vpc = &v
}

func (o CoreDescribeRegionConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccessKeyId != nil {
		toSerialize["access_key_id"] = o.AccessKeyId
	}
	if o.AccessKeySecret != nil {
		toSerialize["access_key_secret"] = o.AccessKeySecret
	}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Project != nil {
		toSerialize["project"] = o.Project
	}
	if o.RecyclingSecurityGroup != nil {
		toSerialize["recycling_security_group"] = o.RecyclingSecurityGroup
	}
	if o.Region != nil {
		toSerialize["region"] = o.Region
	}
	if o.ReverseConnect != nil {
		toSerialize["reverse_connect"] = o.ReverseConnect
	}
	if o.Tenant != nil {
		toSerialize["tenant"] = o.Tenant
	}
	if o.Vendor != nil {
		toSerialize["vendor"] = o.Vendor
	}
	if o.VendorTenant != nil {
		toSerialize["vendor_tenant"] = o.VendorTenant
	}
	if o.Vpc != nil {
		toSerialize["vpc"] = o.Vpc
	}
	return json.Marshal(toSerialize)
}

type NullableCoreDescribeRegionConfigResponse struct {
	value *CoreDescribeRegionConfigResponse
	isSet bool
}

func (v NullableCoreDescribeRegionConfigResponse) Get() *CoreDescribeRegionConfigResponse {
	return v.value
}

func (v *NullableCoreDescribeRegionConfigResponse) Set(val *CoreDescribeRegionConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreDescribeRegionConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreDescribeRegionConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreDescribeRegionConfigResponse(val *CoreDescribeRegionConfigResponse) *NullableCoreDescribeRegionConfigResponse {
	return &NullableCoreDescribeRegionConfigResponse{value: val, isSet: true}
}

func (v NullableCoreDescribeRegionConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreDescribeRegionConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


