/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// OpsDescribeCloudmgrComponentResponse struct for OpsDescribeCloudmgrComponentResponse
type OpsDescribeCloudmgrComponentResponse struct {
	Component *string `json:"component,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status *string `json:"status,omitempty"`
}

// NewOpsDescribeCloudmgrComponentResponse instantiates a new OpsDescribeCloudmgrComponentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsDescribeCloudmgrComponentResponse() *OpsDescribeCloudmgrComponentResponse {
	this := OpsDescribeCloudmgrComponentResponse{}
	return &this
}

// NewOpsDescribeCloudmgrComponentResponseWithDefaults instantiates a new OpsDescribeCloudmgrComponentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsDescribeCloudmgrComponentResponseWithDefaults() *OpsDescribeCloudmgrComponentResponse {
	this := OpsDescribeCloudmgrComponentResponse{}
	return &this
}

// GetComponent returns the Component field value if set, zero value otherwise.
func (o *OpsDescribeCloudmgrComponentResponse) GetComponent() string {
	if o == nil || o.Component == nil {
		var ret string
		return ret
	}
	return *o.Component
}

// GetComponentOk returns a tuple with the Component field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeCloudmgrComponentResponse) GetComponentOk() (*string, bool) {
	if o == nil || o.Component == nil {
		return nil, false
	}
	return o.Component, true
}

// HasComponent returns a boolean if a field has been set.
func (o *OpsDescribeCloudmgrComponentResponse) HasComponent() bool {
	if o != nil && o.Component != nil {
		return true
	}

	return false
}

// SetComponent gets a reference to the given string and assigns it to the Component field.
func (o *OpsDescribeCloudmgrComponentResponse) SetComponent(v string) {
	o.Component = &v
}

// GetInstance returns the Instance field value if set, zero value otherwise.
func (o *OpsDescribeCloudmgrComponentResponse) GetInstance() string {
	if o == nil || o.Instance == nil {
		var ret string
		return ret
	}
	return *o.Instance
}

// GetInstanceOk returns a tuple with the Instance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeCloudmgrComponentResponse) GetInstanceOk() (*string, bool) {
	if o == nil || o.Instance == nil {
		return nil, false
	}
	return o.Instance, true
}

// HasInstance returns a boolean if a field has been set.
func (o *OpsDescribeCloudmgrComponentResponse) HasInstance() bool {
	if o != nil && o.Instance != nil {
		return true
	}

	return false
}

// SetInstance gets a reference to the given string and assigns it to the Instance field.
func (o *OpsDescribeCloudmgrComponentResponse) SetInstance(v string) {
	o.Instance = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *OpsDescribeCloudmgrComponentResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsDescribeCloudmgrComponentResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *OpsDescribeCloudmgrComponentResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *OpsDescribeCloudmgrComponentResponse) SetStatus(v string) {
	o.Status = &v
}

func (o OpsDescribeCloudmgrComponentResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Component != nil {
		toSerialize["component"] = o.Component
	}
	if o.Instance != nil {
		toSerialize["instance"] = o.Instance
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableOpsDescribeCloudmgrComponentResponse struct {
	value *OpsDescribeCloudmgrComponentResponse
	isSet bool
}

func (v NullableOpsDescribeCloudmgrComponentResponse) Get() *OpsDescribeCloudmgrComponentResponse {
	return v.value
}

func (v *NullableOpsDescribeCloudmgrComponentResponse) Set(val *OpsDescribeCloudmgrComponentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsDescribeCloudmgrComponentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsDescribeCloudmgrComponentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsDescribeCloudmgrComponentResponse(val *OpsDescribeCloudmgrComponentResponse) *NullableOpsDescribeCloudmgrComponentResponse {
	return &NullableOpsDescribeCloudmgrComponentResponse{value: val, isSet: true}
}

func (v NullableOpsDescribeCloudmgrComponentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsDescribeCloudmgrComponentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


