/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// OpsListAlertResponse struct for OpsListAlertResponse
type OpsListAlertResponse struct {
	Result *[]OpsDescribeAlertResponse `json:"result,omitempty"`
}

// NewOpsListAlertResponse instantiates a new OpsListAlertResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsListAlertResponse() *OpsListAlertResponse {
	this := OpsListAlertResponse{}
	return &this
}

// NewOpsListAlertResponseWithDefaults instantiates a new OpsListAlertResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsListAlertResponseWithDefaults() *OpsListAlertResponse {
	this := OpsListAlertResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *OpsListAlertResponse) GetResult() []OpsDescribeAlertResponse {
	if o == nil || o.Result == nil {
		var ret []OpsDescribeAlertResponse
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsListAlertResponse) GetResultOk() (*[]OpsDescribeAlertResponse, bool) {
	if o == nil || o.Result == nil {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *OpsListAlertResponse) HasResult() bool {
	if o != nil && o.Result != nil {
		return true
	}

	return false
}

// SetResult gets a reference to the given []OpsDescribeAlertResponse and assigns it to the Result field.
func (o *OpsListAlertResponse) SetResult(v []OpsDescribeAlertResponse) {
	o.Result = &v
}

func (o OpsListAlertResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	return json.Marshal(toSerialize)
}

type NullableOpsListAlertResponse struct {
	value *OpsListAlertResponse
	isSet bool
}

func (v NullableOpsListAlertResponse) Get() *OpsListAlertResponse {
	return v.value
}

func (v *NullableOpsListAlertResponse) Set(val *OpsListAlertResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsListAlertResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsListAlertResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsListAlertResponse(val *OpsListAlertResponse) *NullableOpsListAlertResponse {
	return &NullableOpsListAlertResponse{value: val, isSet: true}
}

func (v NullableOpsListAlertResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsListAlertResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


