/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreDescribeHdfsConfigBriefResponse struct for CoreDescribeHdfsConfigBriefResponse
type CoreDescribeHdfsConfigBriefResponse struct {
	Service *string `json:"service,omitempty"`
	Status *string `json:"status,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
}

// NewCoreDescribeHdfsConfigBriefResponse instantiates a new CoreDescribeHdfsConfigBriefResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreDescribeHdfsConfigBriefResponse() *CoreDescribeHdfsConfigBriefResponse {
	this := CoreDescribeHdfsConfigBriefResponse{}
	return &this
}

// NewCoreDescribeHdfsConfigBriefResponseWithDefaults instantiates a new CoreDescribeHdfsConfigBriefResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreDescribeHdfsConfigBriefResponseWithDefaults() *CoreDescribeHdfsConfigBriefResponse {
	this := CoreDescribeHdfsConfigBriefResponse{}
	return &this
}

// GetService returns the Service field value if set, zero value otherwise.
func (o *CoreDescribeHdfsConfigBriefResponse) GetService() string {
	if o == nil || o.Service == nil {
		var ret string
		return ret
	}
	return *o.Service
}

// GetServiceOk returns a tuple with the Service field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeHdfsConfigBriefResponse) GetServiceOk() (*string, bool) {
	if o == nil || o.Service == nil {
		return nil, false
	}
	return o.Service, true
}

// HasService returns a boolean if a field has been set.
func (o *CoreDescribeHdfsConfigBriefResponse) HasService() bool {
	if o != nil && o.Service != nil {
		return true
	}

	return false
}

// SetService gets a reference to the given string and assigns it to the Service field.
func (o *CoreDescribeHdfsConfigBriefResponse) SetService(v string) {
	o.Service = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CoreDescribeHdfsConfigBriefResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeHdfsConfigBriefResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CoreDescribeHdfsConfigBriefResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CoreDescribeHdfsConfigBriefResponse) SetStatus(v string) {
	o.Status = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *CoreDescribeHdfsConfigBriefResponse) GetTimestamp() string {
	if o == nil || o.Timestamp == nil {
		var ret string
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeHdfsConfigBriefResponse) GetTimestampOk() (*string, bool) {
	if o == nil || o.Timestamp == nil {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *CoreDescribeHdfsConfigBriefResponse) HasTimestamp() bool {
	if o != nil && o.Timestamp != nil {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given string and assigns it to the Timestamp field.
func (o *CoreDescribeHdfsConfigBriefResponse) SetTimestamp(v string) {
	o.Timestamp = &v
}

func (o CoreDescribeHdfsConfigBriefResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Service != nil {
		toSerialize["service"] = o.Service
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Timestamp != nil {
		toSerialize["timestamp"] = o.Timestamp
	}
	return json.Marshal(toSerialize)
}

type NullableCoreDescribeHdfsConfigBriefResponse struct {
	value *CoreDescribeHdfsConfigBriefResponse
	isSet bool
}

func (v NullableCoreDescribeHdfsConfigBriefResponse) Get() *CoreDescribeHdfsConfigBriefResponse {
	return v.value
}

func (v *NullableCoreDescribeHdfsConfigBriefResponse) Set(val *CoreDescribeHdfsConfigBriefResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreDescribeHdfsConfigBriefResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreDescribeHdfsConfigBriefResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreDescribeHdfsConfigBriefResponse(val *CoreDescribeHdfsConfigBriefResponse) *NullableCoreDescribeHdfsConfigBriefResponse {
	return &NullableCoreDescribeHdfsConfigBriefResponse{value: val, isSet: true}
}

func (v NullableCoreDescribeHdfsConfigBriefResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreDescribeHdfsConfigBriefResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


