/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// OpsCreateBalanceAccountResponse struct for OpsCreateBalanceAccountResponse
type OpsCreateBalanceAccountResponse struct {
	Id *string `json:"id,omitempty"`
}

// NewOpsCreateBalanceAccountResponse instantiates a new OpsCreateBalanceAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpsCreateBalanceAccountResponse() *OpsCreateBalanceAccountResponse {
	this := OpsCreateBalanceAccountResponse{}
	return &this
}

// NewOpsCreateBalanceAccountResponseWithDefaults instantiates a new OpsCreateBalanceAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpsCreateBalanceAccountResponseWithDefaults() *OpsCreateBalanceAccountResponse {
	this := OpsCreateBalanceAccountResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *OpsCreateBalanceAccountResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpsCreateBalanceAccountResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *OpsCreateBalanceAccountResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *OpsCreateBalanceAccountResponse) SetId(v string) {
	o.Id = &v
}

func (o OpsCreateBalanceAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableOpsCreateBalanceAccountResponse struct {
	value *OpsCreateBalanceAccountResponse
	isSet bool
}

func (v NullableOpsCreateBalanceAccountResponse) Get() *OpsCreateBalanceAccountResponse {
	return v.value
}

func (v *NullableOpsCreateBalanceAccountResponse) Set(val *OpsCreateBalanceAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOpsCreateBalanceAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOpsCreateBalanceAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpsCreateBalanceAccountResponse(val *OpsCreateBalanceAccountResponse) *NullableOpsCreateBalanceAccountResponse {
	return &NullableOpsCreateBalanceAccountResponse{value: val, isSet: true}
}

func (v NullableOpsCreateBalanceAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpsCreateBalanceAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


