/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreCreateCatalogRequest struct for CoreCreateCatalogRequest
type CoreCreateCatalogRequest struct {
	Catalog *CoreCreateServiceComponentRequest `json:"catalog,omitempty"`
	ChargeChannel *string `json:"chargeChannel,omitempty"`
	ChargeType *string `json:"chargeType,omitempty"`
	Description *string `json:"description,omitempty"`
	Etcd *CoreCreateServiceComponentRequest `json:"etcd,omitempty"`
	ExpiredAt *string `json:"expiredAt,omitempty"`
	Extras *CoreCreateServiceIaasExtraRequest `json:"extras,omitempty"`
	Fdb *CoreCreateServiceComponentRequest `json:"fdb,omitempty"`
	Metadata *map[string]interface{} `json:"metadata,omitempty"`
	Monitor *CoreCreateServiceComponentRequest `json:"monitor,omitempty"`
	Name *string `json:"name,omitempty"`
	Oss *CoreCreateServiceOssZoneRequest `json:"oss,omitempty"`
}

// NewCoreCreateCatalogRequest instantiates a new CoreCreateCatalogRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreCreateCatalogRequest() *CoreCreateCatalogRequest {
	this := CoreCreateCatalogRequest{}
	return &this
}

// NewCoreCreateCatalogRequestWithDefaults instantiates a new CoreCreateCatalogRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreCreateCatalogRequestWithDefaults() *CoreCreateCatalogRequest {
	this := CoreCreateCatalogRequest{}
	return &this
}

// GetCatalog returns the Catalog field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetCatalog() CoreCreateServiceComponentRequest {
	if o == nil || o.Catalog == nil {
		var ret CoreCreateServiceComponentRequest
		return ret
	}
	return *o.Catalog
}

// GetCatalogOk returns a tuple with the Catalog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetCatalogOk() (*CoreCreateServiceComponentRequest, bool) {
	if o == nil || o.Catalog == nil {
		return nil, false
	}
	return o.Catalog, true
}

// HasCatalog returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasCatalog() bool {
	if o != nil && o.Catalog != nil {
		return true
	}

	return false
}

// SetCatalog gets a reference to the given CoreCreateServiceComponentRequest and assigns it to the Catalog field.
func (o *CoreCreateCatalogRequest) SetCatalog(v CoreCreateServiceComponentRequest) {
	o.Catalog = &v
}

// GetChargeChannel returns the ChargeChannel field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetChargeChannel() string {
	if o == nil || o.ChargeChannel == nil {
		var ret string
		return ret
	}
	return *o.ChargeChannel
}

// GetChargeChannelOk returns a tuple with the ChargeChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetChargeChannelOk() (*string, bool) {
	if o == nil || o.ChargeChannel == nil {
		return nil, false
	}
	return o.ChargeChannel, true
}

// HasChargeChannel returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasChargeChannel() bool {
	if o != nil && o.ChargeChannel != nil {
		return true
	}

	return false
}

// SetChargeChannel gets a reference to the given string and assigns it to the ChargeChannel field.
func (o *CoreCreateCatalogRequest) SetChargeChannel(v string) {
	o.ChargeChannel = &v
}

// GetChargeType returns the ChargeType field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetChargeType() string {
	if o == nil || o.ChargeType == nil {
		var ret string
		return ret
	}
	return *o.ChargeType
}

// GetChargeTypeOk returns a tuple with the ChargeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetChargeTypeOk() (*string, bool) {
	if o == nil || o.ChargeType == nil {
		return nil, false
	}
	return o.ChargeType, true
}

// HasChargeType returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasChargeType() bool {
	if o != nil && o.ChargeType != nil {
		return true
	}

	return false
}

// SetChargeType gets a reference to the given string and assigns it to the ChargeType field.
func (o *CoreCreateCatalogRequest) SetChargeType(v string) {
	o.ChargeType = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CoreCreateCatalogRequest) SetDescription(v string) {
	o.Description = &v
}

// GetEtcd returns the Etcd field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetEtcd() CoreCreateServiceComponentRequest {
	if o == nil || o.Etcd == nil {
		var ret CoreCreateServiceComponentRequest
		return ret
	}
	return *o.Etcd
}

// GetEtcdOk returns a tuple with the Etcd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetEtcdOk() (*CoreCreateServiceComponentRequest, bool) {
	if o == nil || o.Etcd == nil {
		return nil, false
	}
	return o.Etcd, true
}

// HasEtcd returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasEtcd() bool {
	if o != nil && o.Etcd != nil {
		return true
	}

	return false
}

// SetEtcd gets a reference to the given CoreCreateServiceComponentRequest and assigns it to the Etcd field.
func (o *CoreCreateCatalogRequest) SetEtcd(v CoreCreateServiceComponentRequest) {
	o.Etcd = &v
}

// GetExpiredAt returns the ExpiredAt field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetExpiredAt() string {
	if o == nil || o.ExpiredAt == nil {
		var ret string
		return ret
	}
	return *o.ExpiredAt
}

// GetExpiredAtOk returns a tuple with the ExpiredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetExpiredAtOk() (*string, bool) {
	if o == nil || o.ExpiredAt == nil {
		return nil, false
	}
	return o.ExpiredAt, true
}

// HasExpiredAt returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasExpiredAt() bool {
	if o != nil && o.ExpiredAt != nil {
		return true
	}

	return false
}

// SetExpiredAt gets a reference to the given string and assigns it to the ExpiredAt field.
func (o *CoreCreateCatalogRequest) SetExpiredAt(v string) {
	o.ExpiredAt = &v
}

// GetExtras returns the Extras field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetExtras() CoreCreateServiceIaasExtraRequest {
	if o == nil || o.Extras == nil {
		var ret CoreCreateServiceIaasExtraRequest
		return ret
	}
	return *o.Extras
}

// GetExtrasOk returns a tuple with the Extras field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetExtrasOk() (*CoreCreateServiceIaasExtraRequest, bool) {
	if o == nil || o.Extras == nil {
		return nil, false
	}
	return o.Extras, true
}

// HasExtras returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasExtras() bool {
	if o != nil && o.Extras != nil {
		return true
	}

	return false
}

// SetExtras gets a reference to the given CoreCreateServiceIaasExtraRequest and assigns it to the Extras field.
func (o *CoreCreateCatalogRequest) SetExtras(v CoreCreateServiceIaasExtraRequest) {
	o.Extras = &v
}

// GetFdb returns the Fdb field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetFdb() CoreCreateServiceComponentRequest {
	if o == nil || o.Fdb == nil {
		var ret CoreCreateServiceComponentRequest
		return ret
	}
	return *o.Fdb
}

// GetFdbOk returns a tuple with the Fdb field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetFdbOk() (*CoreCreateServiceComponentRequest, bool) {
	if o == nil || o.Fdb == nil {
		return nil, false
	}
	return o.Fdb, true
}

// HasFdb returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasFdb() bool {
	if o != nil && o.Fdb != nil {
		return true
	}

	return false
}

// SetFdb gets a reference to the given CoreCreateServiceComponentRequest and assigns it to the Fdb field.
func (o *CoreCreateCatalogRequest) SetFdb(v CoreCreateServiceComponentRequest) {
	o.Fdb = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetMetadata() map[string]interface{} {
	if o == nil || o.Metadata == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetMetadataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CoreCreateCatalogRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = &v
}

// GetMonitor returns the Monitor field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetMonitor() CoreCreateServiceComponentRequest {
	if o == nil || o.Monitor == nil {
		var ret CoreCreateServiceComponentRequest
		return ret
	}
	return *o.Monitor
}

// GetMonitorOk returns a tuple with the Monitor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetMonitorOk() (*CoreCreateServiceComponentRequest, bool) {
	if o == nil || o.Monitor == nil {
		return nil, false
	}
	return o.Monitor, true
}

// HasMonitor returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasMonitor() bool {
	if o != nil && o.Monitor != nil {
		return true
	}

	return false
}

// SetMonitor gets a reference to the given CoreCreateServiceComponentRequest and assigns it to the Monitor field.
func (o *CoreCreateCatalogRequest) SetMonitor(v CoreCreateServiceComponentRequest) {
	o.Monitor = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CoreCreateCatalogRequest) SetName(v string) {
	o.Name = &v
}

// GetOss returns the Oss field value if set, zero value otherwise.
func (o *CoreCreateCatalogRequest) GetOss() CoreCreateServiceOssZoneRequest {
	if o == nil || o.Oss == nil {
		var ret CoreCreateServiceOssZoneRequest
		return ret
	}
	return *o.Oss
}

// GetOssOk returns a tuple with the Oss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreCreateCatalogRequest) GetOssOk() (*CoreCreateServiceOssZoneRequest, bool) {
	if o == nil || o.Oss == nil {
		return nil, false
	}
	return o.Oss, true
}

// HasOss returns a boolean if a field has been set.
func (o *CoreCreateCatalogRequest) HasOss() bool {
	if o != nil && o.Oss != nil {
		return true
	}

	return false
}

// SetOss gets a reference to the given CoreCreateServiceOssZoneRequest and assigns it to the Oss field.
func (o *CoreCreateCatalogRequest) SetOss(v CoreCreateServiceOssZoneRequest) {
	o.Oss = &v
}

func (o CoreCreateCatalogRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Catalog != nil {
		toSerialize["catalog"] = o.Catalog
	}
	if o.ChargeChannel != nil {
		toSerialize["chargeChannel"] = o.ChargeChannel
	}
	if o.ChargeType != nil {
		toSerialize["chargeType"] = o.ChargeType
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Etcd != nil {
		toSerialize["etcd"] = o.Etcd
	}
	if o.ExpiredAt != nil {
		toSerialize["expiredAt"] = o.ExpiredAt
	}
	if o.Extras != nil {
		toSerialize["extras"] = o.Extras
	}
	if o.Fdb != nil {
		toSerialize["fdb"] = o.Fdb
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.Monitor != nil {
		toSerialize["monitor"] = o.Monitor
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Oss != nil {
		toSerialize["oss"] = o.Oss
	}
	return json.Marshal(toSerialize)
}

type NullableCoreCreateCatalogRequest struct {
	value *CoreCreateCatalogRequest
	isSet bool
}

func (v NullableCoreCreateCatalogRequest) Get() *CoreCreateCatalogRequest {
	return v.value
}

func (v *NullableCoreCreateCatalogRequest) Set(val *CoreCreateCatalogRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreCreateCatalogRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreCreateCatalogRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreCreateCatalogRequest(val *CoreCreateCatalogRequest) *NullableCoreCreateCatalogRequest {
	return &NullableCoreCreateCatalogRequest{value: val, isSet: true}
}

func (v NullableCoreCreateCatalogRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreCreateCatalogRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


