/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreStartServiceRequest struct for CoreStartServiceRequest
type CoreStartServiceRequest struct {
	StopAt *string `json:"stop_at,omitempty"`
}

// NewCoreStartServiceRequest instantiates a new CoreStartServiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreStartServiceRequest() *CoreStartServiceRequest {
	this := CoreStartServiceRequest{}
	return &this
}

// NewCoreStartServiceRequestWithDefaults instantiates a new CoreStartServiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreStartServiceRequestWithDefaults() *CoreStartServiceRequest {
	this := CoreStartServiceRequest{}
	return &this
}

// GetStopAt returns the StopAt field value if set, zero value otherwise.
func (o *CoreStartServiceRequest) GetStopAt() string {
	if o == nil || o.StopAt == nil {
		var ret string
		return ret
	}
	return *o.StopAt
}

// GetStopAtOk returns a tuple with the StopAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreStartServiceRequest) GetStopAtOk() (*string, bool) {
	if o == nil || o.StopAt == nil {
		return nil, false
	}
	return o.StopAt, true
}

// HasStopAt returns a boolean if a field has been set.
func (o *CoreStartServiceRequest) HasStopAt() bool {
	if o != nil && o.StopAt != nil {
		return true
	}

	return false
}

// SetStopAt gets a reference to the given string and assigns it to the StopAt field.
func (o *CoreStartServiceRequest) SetStopAt(v string) {
	o.StopAt = &v
}

func (o CoreStartServiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.StopAt != nil {
		toSerialize["stop_at"] = o.StopAt
	}
	return json.Marshal(toSerialize)
}

type NullableCoreStartServiceRequest struct {
	value *CoreStartServiceRequest
	isSet bool
}

func (v NullableCoreStartServiceRequest) Get() *CoreStartServiceRequest {
	return v.value
}

func (v *NullableCoreStartServiceRequest) Set(val *CoreStartServiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreStartServiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreStartServiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreStartServiceRequest(val *CoreStartServiceRequest) *NullableCoreStartServiceRequest {
	return &NullableCoreStartServiceRequest{value: val, isSet: true}
}

func (v NullableCoreStartServiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreStartServiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


