/*
 * Cloud Manager API
 *
 * Cloud Manager Restful API Documentation.
 *
 * API version: v2.0
 * Contact: wang@hashdata.cn
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cloudmgr

import (
	"encoding/json"
)

// CoreDescribeZoneConfigResponse struct for CoreDescribeZoneConfigResponse
type CoreDescribeZoneConfigResponse struct {
	CreatedAt *string `json:"created_at,omitempty"`
	Id *string `json:"id,omitempty"`
	Tenant *string `json:"tenant,omitempty"`
	Vendor *string `json:"vendor,omitempty"`
	Vxnet *string `json:"vxnet,omitempty"`
	Zone *string `json:"zone,omitempty"`
}

// NewCoreDescribeZoneConfigResponse instantiates a new CoreDescribeZoneConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCoreDescribeZoneConfigResponse() *CoreDescribeZoneConfigResponse {
	this := CoreDescribeZoneConfigResponse{}
	return &this
}

// NewCoreDescribeZoneConfigResponseWithDefaults instantiates a new CoreDescribeZoneConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCoreDescribeZoneConfigResponseWithDefaults() *CoreDescribeZoneConfigResponse {
	this := CoreDescribeZoneConfigResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CoreDescribeZoneConfigResponse) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeZoneConfigResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CoreDescribeZoneConfigResponse) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *CoreDescribeZoneConfigResponse) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CoreDescribeZoneConfigResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeZoneConfigResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CoreDescribeZoneConfigResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CoreDescribeZoneConfigResponse) SetId(v string) {
	o.Id = &v
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *CoreDescribeZoneConfigResponse) GetTenant() string {
	if o == nil || o.Tenant == nil {
		var ret string
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeZoneConfigResponse) GetTenantOk() (*string, bool) {
	if o == nil || o.Tenant == nil {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *CoreDescribeZoneConfigResponse) HasTenant() bool {
	if o != nil && o.Tenant != nil {
		return true
	}

	return false
}

// SetTenant gets a reference to the given string and assigns it to the Tenant field.
func (o *CoreDescribeZoneConfigResponse) SetTenant(v string) {
	o.Tenant = &v
}

// GetVendor returns the Vendor field value if set, zero value otherwise.
func (o *CoreDescribeZoneConfigResponse) GetVendor() string {
	if o == nil || o.Vendor == nil {
		var ret string
		return ret
	}
	return *o.Vendor
}

// GetVendorOk returns a tuple with the Vendor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeZoneConfigResponse) GetVendorOk() (*string, bool) {
	if o == nil || o.Vendor == nil {
		return nil, false
	}
	return o.Vendor, true
}

// HasVendor returns a boolean if a field has been set.
func (o *CoreDescribeZoneConfigResponse) HasVendor() bool {
	if o != nil && o.Vendor != nil {
		return true
	}

	return false
}

// SetVendor gets a reference to the given string and assigns it to the Vendor field.
func (o *CoreDescribeZoneConfigResponse) SetVendor(v string) {
	o.Vendor = &v
}

// GetVxnet returns the Vxnet field value if set, zero value otherwise.
func (o *CoreDescribeZoneConfigResponse) GetVxnet() string {
	if o == nil || o.Vxnet == nil {
		var ret string
		return ret
	}
	return *o.Vxnet
}

// GetVxnetOk returns a tuple with the Vxnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeZoneConfigResponse) GetVxnetOk() (*string, bool) {
	if o == nil || o.Vxnet == nil {
		return nil, false
	}
	return o.Vxnet, true
}

// HasVxnet returns a boolean if a field has been set.
func (o *CoreDescribeZoneConfigResponse) HasVxnet() bool {
	if o != nil && o.Vxnet != nil {
		return true
	}

	return false
}

// SetVxnet gets a reference to the given string and assigns it to the Vxnet field.
func (o *CoreDescribeZoneConfigResponse) SetVxnet(v string) {
	o.Vxnet = &v
}

// GetZone returns the Zone field value if set, zero value otherwise.
func (o *CoreDescribeZoneConfigResponse) GetZone() string {
	if o == nil || o.Zone == nil {
		var ret string
		return ret
	}
	return *o.Zone
}

// GetZoneOk returns a tuple with the Zone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CoreDescribeZoneConfigResponse) GetZoneOk() (*string, bool) {
	if o == nil || o.Zone == nil {
		return nil, false
	}
	return o.Zone, true
}

// HasZone returns a boolean if a field has been set.
func (o *CoreDescribeZoneConfigResponse) HasZone() bool {
	if o != nil && o.Zone != nil {
		return true
	}

	return false
}

// SetZone gets a reference to the given string and assigns it to the Zone field.
func (o *CoreDescribeZoneConfigResponse) SetZone(v string) {
	o.Zone = &v
}

func (o CoreDescribeZoneConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Tenant != nil {
		toSerialize["tenant"] = o.Tenant
	}
	if o.Vendor != nil {
		toSerialize["vendor"] = o.Vendor
	}
	if o.Vxnet != nil {
		toSerialize["vxnet"] = o.Vxnet
	}
	if o.Zone != nil {
		toSerialize["zone"] = o.Zone
	}
	return json.Marshal(toSerialize)
}

type NullableCoreDescribeZoneConfigResponse struct {
	value *CoreDescribeZoneConfigResponse
	isSet bool
}

func (v NullableCoreDescribeZoneConfigResponse) Get() *CoreDescribeZoneConfigResponse {
	return v.value
}

func (v *NullableCoreDescribeZoneConfigResponse) Set(val *CoreDescribeZoneConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCoreDescribeZoneConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCoreDescribeZoneConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCoreDescribeZoneConfigResponse(val *CoreDescribeZoneConfigResponse) *NullableCoreDescribeZoneConfigResponse {
	return &NullableCoreDescribeZoneConfigResponse{value: val, isSet: true}
}

func (v NullableCoreDescribeZoneConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCoreDescribeZoneConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


